[package]
name = "web"

version.workspace = true
edition.workspace = true

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
leptos = { version = "0.7.3", features = ["csr"] }
leptos_meta = "0.7.3"
log = "0.4.22"
