[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"
filehash = true
inject_scripts = true
minify = "on_release"

# Generating a nonce with Trunk prevents the stylesheet from loading. This might
# be a bug either in Trunk or Leptos, but for now we are simply disabling the
# feature. See https://github.com/trunk-rs/trunk/issues/941 for more details.
# TODO: Research how this setting can be removed
create_nonce = false

[watch]
watch = []
ignore = []

[serve]
addresses = ["127.0.0.1"]
port = 3000
open = false
